const paragraphs = [
    "The quick brown fox jumps over the lazy dog. Typing fast and accurately is a valuable skill for everyone.",
    "Practice makes perfect. The more you type, the better your speed and accuracy will become.",
    "Consistent daily typing can help you improve your words per minute and reduce mistakes.",
    "Challenge yourself with new paragraphs and try to beat your previous high score each time.",
    "Focus on accuracy first, then gradually increase your speed as you become more comfortable.",
    "Typing games are a fun way to test your skills and track your progress over time.",
    "Remember to sit up straight, keep your wrists relaxed, and use all your fingers while typing.",
    "Set small goals for each session, such as increasing your WPM or reducing your error rate.",
    "Take regular breaks to avoid fatigue and maintain your best performance during practice.",
    "Celebrate your improvements and keep pushing yourself to reach new typing milestones.",
    "Learning to type efficiently can save you time and make computer work much easier.",
    "Try not to look at the keyboard. Trust your muscle memory and let your fingers do the work.",
    "Stay motivated by tracking your progress and rewarding yourself for reaching your goals.",
    "Typing is a lifelong skill that will benefit you in school, work, and everyday life.",
    "Use online resources and typing tests to find new challenges and keep your practice interesting.",
    "Accuracy is more important than speed. Slow down if you find yourself making too many mistakes.",
    "With patience and persistence, anyone can become a fast and accurate typist.",
    "Try different keyboard layouts and find the one that feels most comfortable for you.",
    "Share your progress with friends and challenge them to typing competitions.",
    "Every great typist started as a beginner. Keep practicing and you will see results!"
];